repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        types: [file]
        files: ^dotctrl/*
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        types: [file]
        files: ^dotctrl/*
